---

- hosts: dc
  sudo: yes

  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache Service
    apt: name=apache2 state=present

  - name: Deploy Apache Index Page
    copy: src=templates/index.html dest=/var/www/html/index.html





